const actionTypes = {
  SET_GROUP: "SET_GROUP",
  NEXT_WEEK: "NEXT_WEEK",
  PREVIOUS_WEEK: "PREVIOUS_WEEK",
  TODAY: "TODAY",
  SET_DATE: "SET_DATE",
  DATA_REQUEST_INNITIATED: " DATA_REQUEST_INNITIATED",
  DATA_REQUEST_SUCCESSFUL: "DATA_REQUEST_SUCCESSFUL",
  DATA_REQUEST_FAILED: "DATA_REQUEST_FAILED",
};

export default actionTypes;
