const constants = {
  SET_BOOKABLE: "SET_BOOKABLE",
  NEXT_BOOKABLE: "NEXT_BOOKABLE",
  TOGGLE_HAS_DETAILS: "TOGGLE_HAS_DETAILS",
  SET_GROUP: "SET_GROUP",
  NEXT_WEEK: "NEXT_WEEK",
  PREVIOUS_WEEK: "PREVIOUS_WEEK",
  TODAY: "TODAY",
  SET_DATE: "SET_DATE",
  FETCH_BOOKABLES_REQUEST: "FETCH_BOOKABLES_REQUEST",
  FETCH_BOOKABLES_SUCCESS: "FETCH_BOOKABLES_SUCCESS",
  FETCH_BOOKABLES_ERROR: "FETCH_BOOKABLES_ERROR",
  FETCH_USERS_REQUEST: "FETCH_USERS_REQUEST",
  FETCH_USERS_SUCCESS: "FETCH_USERS_SUCCESS",
  FETCH_USERS_ERROR: "FETCH_USERS_ERROR",
  SET_USER_INDEX: "SET_USER_INDEX",
};

export default constants;
